FROM  gcc:9.4 as builder
COPY hello.c /src/hello.c
WORKDIR /src
RUN gcc --static -o hello hello.c


FROM alpine:3.13.5
COPY --from=builder  /src/hello /src/hello
ENTRYPOINT ["/src/hello"]
CMD []