version: "3.8"

services: 
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    networks:
      - netes
    volumes:
      - ../data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
#这里要注意，es和eshd要在相同网络才能被links
networks: 
  netes:
    external: false 