version: "3.8"

services: 
  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: elasticsearch
    networks:
      - netes
    volumes:
      - ../data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  elastichd:
    image: containerize/elastichd:latest
    container_name: elasticsearch-hd
    networks:
      - netes
    ports: 
      - "9800:9800"
    depends_on:
      - "elasticsearch"
    links: 
      - "elasticsearch"

#这里要注意，es和eshd要在相同网络才能被links
networks: 
  netes:
    external: false 