version: "3.8"

services: # 容器
  myredis: 
    image: redis:latest
    container_name: my_redis
    ports: 
      - 6379:6379
    volumes:
      - D:/data/docker/redis/data:/data
volumes:
  data:
    driver: local