version: "3.8"

services: # 容器
  myredis: 
    image: redis:latest
    ports: 
      - 6379:6379
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - D:/data/docker/mysql/data:/var/lib/mysql
      - D:/data/docker/mysql/conf/my.cnf:/etc/my.cnf:ro
      - D:/data/docker/mysql/init:/docker-entrypoint-initdb.d/
volumes:
  data:
    driver: local