version: "3.8"
services:
  springboot-hello-world: 
    image: springboot-hello-world:latest
    build:
      context: ./springboot
      dockerfile: Dockerfile
    container_name: springboot-hello-world
    ports: 
      - 8080:8080