version: "3.8"

services: # 容器
  myredis: 
    image: redis:latest
    container_name: my_redis
    command: redis-server --requirepass 123456
    ports: 
      - 6379:6379
    volumes:
      - D:/data/docker/redis/data:/data
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - D:/data/docker/mysql/data:/var/lib/mysql
      - D:/data/docker/mysql/conf/my.cnf:/etc/my.cnf:ro
      - D:/data/docker/mysql/init:/docker-entrypoint-initdb.d/
volumes:
  data:
    driver: local